### ISSUE TITLE
Clarity about Duty to Defend

### ISSUE THREAD

**Issue by staking** [lemonade-hq/policy-2.0#11]
Standard Insurance Policies include a **duty to defend** provision under the liability policy, the insurance will cover the associated legal defense costs.

Simple Language: The policy will cover you up to you liability limits (state limit) if you are accused of causing harm, even if you are not responsible.

It should also clarify if coverage is claims made or claims occurred basis in simple language.

**Comment by JohnSPeters** [comment]
@staking Thanks for the comments!  Our intention is to provide defense coverage in the policy, but it is a tricky issue so we'd like to get the wording right.  Here's how we tried to do it:

The start of the Liability section says:
"This policy protects you if someone claims you’ve caused them bodily injury or property damage. If needed, we’ll provide legal defense at our own expense and pay the damages on your behalf."

On the limit, we say:
"The maximum amount we’ll pay in damages is $100,000 per year."  
The intent is that there is only a limit to the damages we pay on your behalf, and the defense we provide would be in addition to the policy limit.

The policy is intended to be a 'claims occurred' or an 'occurrence' policy.  Early in the policy, we say:
"This policy covers events that started after March 12, 2017 at 1:30pm, and before March 12, 2018, 1:30pm."

Can you let us know if you think we've explained it sufficiently, or if there is other language changes you'd recommend?

Thanks for helping us improve this!

John

**Comment by georgieflood** [comment]
Are you sure this is an occurrence policy? As in you can claim for an event that occurred during the term of the insurance even if the term has expired? 

If it is an occurrence policy rather than a claims made policy I agree with @staking you need to state that much more clearly. Is that usual for renters/homeowners insurance?

**Comment by JohnSPeters** [comment]
In the U.S., standard renters/homeowners policies are occurrence policies.  If you think that is unclear, is there a logical spot we should add something that would be understandable to a normal consumer?

**Comment by georgieflood** [comment]
I would put it in Cancellation and Renewal.

"This is what is known as an 'occurrence' policy. This means that even if you elect not to renew (or your renewal is canceled by us) you are still covered for claims made regarding events that occurred during the policy period."

**Comment by ckvo** [comment]
@georgieflood We've had a think about whether to include this clarification. From our experience to date, this hasn't been observed to be a significant issue. Customers have filed claims (or at least have reached out to us to check whether they are able to file a claim) on cancelled policies which indicates that customers are aware that there may be coverage.  

Given that these are edge cases, and the omission of the clarification will not affect coverage, we'd prefer to leave the wording as is. If we receive similar feedback that there needs to be further clarity, we can reconsider it at a later date. Thanks for the considered feedback!
