### ISSUE TITLE
Clarification around "stuff that's used for your business"

### ISSUE THREAD

**Issue by Koruna18** [lemonade-hq/policy-2.0#15]
"We don’t cover cash, assault weapons, stuff that’s used for your business, or things that you willingly handed over to someone else to look after."

Does this mean company-issued equipment, such as the laptop issued to me that I often take home to finish work? Does this refer to physical goods that I sell? Does it cover a mahogany desk that I use in my home office?

**Comment by JohnSPeters** [comment]
Hey @Koruna18 - thanks for the question.  Business property is always a tricky area, especially these days where people have multiple jobs and work from everywhere.  In general, we are trying to avoid covering things that are best suited for a commercial (i.e., corporate) insurance policy, like equipment and inventory.  On your specific questions:

Company-issued equipment - typically this is owned by the company, not by you.  So if you don't own it individually, it is not covered.

Physical goods you sell - this is really business inventory, and again - not covered.

Your mahogany desk - this one is trickier.  If you have a home office, and it is predominately used for that purpose (e.g., it has a separate entrance, you have clients come in to meet there), then it is an 'office' and is not covered.  But, if the desk is in your den, is used part time by you as a consultant or designer, and the rest of the time is for personal use (e.g., kids doing their homework), then it is part of your home and would be covered.

If you work for yourself, we try to apply a reasonable person test.  If you are a great photographer and sell your pictures (making more than a few thousand a year), we're going to ask about the camera.  If you take all the photos with your iPhone, it would be covered.  If you have a $5k camera with a huge lens, we'd consider that 'business use' and it would not be covered.

Note - we are planning a 'business' add-on coverage that would include some property and also liability protection, but that would be exactly that - an additional coverage.

**Comment by Koruna18** [comment]
I think this makes sense. Maybe the language should be changed to "stuff that is primarily used for your business" - I think this would remove the ambiguity around the mahogany desk example, while still making it very clear that things like inventory stored at your apartment wouldn't be covered.

I work in the insurance industry on the data end of things so policy wording may not be my forte, but I'm extremely interested in this initiative so I wanted to participate however possible.

**Comment by craiglinton** [comment]
Would a freelancer's laptop, used for all things personal and business, be business property? Would you look to see if the freelancer expensed the item on a tax return?

**Comment by ckvo** [comment]
@craiglinton Sorry for the delay on getting back to you! In terms of a freelancer's laptop, we'd apply a similar thought process to the mahogany desk example. If the laptop is primarily used for business use (e.g. is a separate laptop that has been set up with unique specifications and software), this is unlikely to be covered. But if you only have one laptop which you use both for business and personally, this is something we'd normally cover.

@Koruna18 I'll submit a pull request on your behalf making the change to specify "stuff that is **primarily** used for you business". Thanks for the suggestion. You'll see this merged into the base code soon.
