### ISSUE TITLE
What is the plan?

### ISSUE THREAD

**Issue by jnmclarty** [lemonade-hq/policy-2.0#18]
Hi folks,

This is going to be a pretty interesting case study to watch unfold if it gets legs, and I applaud Lemonade for dipping their toe into this thought-leadership with this experiment.  I'm wondering about the longer run plan for the execution and implementation details, juxtaposed against the blurb below.  It would impact if, how, and how much, I and likely others contribute.  As is, there isn't enough for me to jump in to help, since its too early.

> This draft was created in consultation with state regulators, and will be submitted to all states once the community has had its say. Until the approvals are in, Lemonade will continue to offer an industry-standard policy, with a view to letting users switch to Policy 2.0 once its available in their state.

Let me expand:

Right now, this repository is an example of one single policy for Jane.  I'm not an expert on how insurance policies work, nor am I American.  From your blurb above, and the contents of this repo, does this mean you're expecting contributors to only help author a document which would be used as some kind of appendix in a proposal to a new standard for the entire industry, just in the US? Or is this example renters insurance something Lemonade can sell with or without a government's approval?  And how are you going to organize other Countries? Or even just edge cases required for individual states? etc.

Maybe my question lacks context of the industry and your vision here, but whatever the answers are, I'm not actually personally concerned with which way the answer goes.  But the answers, in my humble opinion, should be captured at the principle-level, in both a Vision statement, perhaps in the README.md as well as a contributor's guide.  These sections would evolve over time, and that's okay.   

I personally stumbled into this repo, expecting to contribute to a template system of some kind, not one example.  I instantly assumed, insurance policies would end up versioned like software.  And built custom to me via config files, or a web app Lemonade would create for non-software-dev consumers.  I was immediately wondering to myself "This isn't a template, this is just an example", then froze.

**Comment by JohnSPeters** [comment]
@jnmclarty thanks for the thoughtful post.  I'll expand a bit.  This is a sample policy, but we'd expect to sell this basic policy to all renters in the U.S.  While you will be able to add and delete coverages to 'tailor' it to you, it will have a common core policy language and set of coverages.

This very well could be used in markets outside of the U.S., but we'd need to explore local market expectations and regulations first.  If you have advice for your country, I'm all ears.

This is just our effort to improve the industry standard policy, first and foremost for our customers.  We have chosen to make it publically available, and any insurance company could use it if they chose. If this is successful and customers valued the simplicity and transparency, it would be great if it became the industry standard. 

This does need to be approved by each individual state, and their rules do vary.  We've discussed it with a few, and their reactions are overall very positive.  Any state specific regulations would need to be adjustments to the policy, and we've left a section for those.  We will strive to make this as consistent across the U.S. as possible.

**Comment by jnmclarty** [comment]
Ok.  I would say your README.md needs to be updated to reflect the direction your taking.

I think it was this line here, that caused me the most confusion:

**Digital**: Each Policy 2.0 will be unique and dynamically-generated, based on the choices the user made.

The way it reads, it makes it sound like this repo will eventually contain source code which will enable the dynamically-generated policy.
