### ISSUE TITLE
Clarification of "per year" aggregate reimbursement limit

### ISSUE THREAD

**Issue by craiglinton** [lemonade-hq/policy-2.0#19]
Several part of the policy mention "per year" limits, e.g.:
> These amounts indicate the maximum we will reimburse you, in total, per year - even if the losses you suffer are larger.

Your policyholders might misinterpret this to mean per calendar year (e.g., 2017, 2018) rather than per _policy_ year, which is the meaning that I suspect that you intend. Moreover, if you sell a policy for longer than a 12-month term (maybe in the plans down the road), your policyholder may expect to re-up the limits after 12 months.

Also, the deductible section doesn't specify whether it's per claim, per item, or per policy year. It's unclear whether it applies to items or also to things like accommodations while the home is unlivable.

**Comment by JohnSPeters** [comment]
@craiglinton The policy limit is per policy year, not calendar year.  Very fair comment that it could be misinterpreted, and we should clarify it.

The deductible is intended to be applied per claim, regardless of the coverages involved.  So if you have a contents and loss of use claim, the deductible applies once.  If you have a loss of use only claim, one deductible applies.

**Comment by ckvo** [comment]
@craiglinton We'll make a pull request on your behalf to clarify that "per year" does in fact mean "per policy year". We'll make that change in one of the leading sections at the top of the wording to ensure that it seen by customers and reflects how "per year" should be interpreted throughout the policy. Thanks again for identifying this - you'll see the change in the base code shortly.

**Comment by unitof** [comment]
@ckvo Did this PR end up getting made? I can't find it. If not, happy to make it myself.

**Comment by ckvo** [comment]
@unitof It looks as though it hasn't as yet - if you can make the PR that would be fantastic 👍
