### ISSUE TITLE
Include some sample cases and how they would be handled

### ISSUE THREAD

**Issue by tachang** [lemonade-hq/policy-2.0#21]
Would be nice to add so people can get a general idea of what they would get when insurance pays out.

**Comment by ckvo** [comment]
Hi @tachang - thanks for the feedback. 

We've actually included various examples throughout the wording to try to help clarify how the coverage would interact in a real world situation. For example:

> We cover stuff you own and have in your possession. If you willingly handed your things to someone else, they’re responsible. So if your stuff was damaged during shipping, at the dry cleaners, while on loan to a friend, or never came off your flight to Hawaii - it’s not covered.

We've also included a specific example about how the deductible works to clarify the dollar payout as this is a concept which is specific to insurance.

> For example, if you have an approved claim that amounts to $7,000, we will end up paying you $6,500 (after we deduct the $500 ‘deductible’). It also means there’s no point in filing claims for anything less than the $500.

Are these the kinds of examples you were envisaging?
