### ISSUE TITLE
Release the 1.0 policy's specs

### ISSUE THREAD

**Issue by gabrielrondon** [lemonade-hq/policy-2.0#22]
When going open-source, even when the decision is to create something new, it would be useful to have a base now, as you refer this policy as 2.0. So, where is the 1.0? Release public at least the specs to people inspire and help you and the community.

**Comment by ckvo** [comment]
Hey @gabrielrondon - good point. Here's a link to the current policy wordings that we use, which are based on standard insurance industry wording: [https://www.lemonade.com/terms-of-service](url)
Check out one of the sample "Renters (HO4)" policies in the section titled "Digital Assistant".

As you'll see, policy '1.0' is not an easy read. This should help to provide more context on why we have embarked on this project and why we're seeking the opinions of all interested parties to produce something which is simpler, more approachable, and more relevant to people today. Would love to hear your thoughts.

**Comment by gabrielrondon** [comment]
I think we could have a layer to create a policy. It means working in two layers. Basically: 
1st layer: A framework to build other policies
2nd layer: The Policies itself (with variations per product or geo-localization rules, for instance).

Talking about the first layer (the framework to build policies), I think it would be a nice idea to adopt the same language, like OpenAPI 3.0.1. Since all the policies are the outputs of this framework, I think they will be easier to read, compare, analyze and we would assure that the policies have a common base. If you like the idea, maybe I can write a first version, using OpenAPI language, for the "framework of policies".

**Comment by ckvo** [comment]
Hi @gabrielrondon - it's a great idea in concept and could be a good place to start if the plan was to produce a framework for all insurance policies across all different types of insurance (e.g. auto, travel, commercial, reinsurance!). Alas, the scope of such a project is probably too wide-ranging at this stage but it's one we can loop back to if we do start looking outside of the renters/homeowners insurance space. Appreciate the offer of assistance to develop the first 'framework' - we'll be sure to keep it in mind.
