### ISSUE TITLE
Define Item

### ISSUE THREAD

**Issue by SoCalMark** [lemonade-hq/policy-2.0#31]
Are a pair of earrings one item or two items.  Is a set of golf clubs one or 4 items.

**Comment by ckvo** [comment]
Hey @SoCalMark - great point and is something we should better clarify. The intention would be for pairs/sets to be considered as one item. It's something that we had in our earlier drafts but weren't able to come to a consensus on. Do you have any suggestions on how we should incorporate this? Perhaps something after the first sentence in the section copied below?

> Items worth up to $2,500 are covered automatically, but we won’t pay more per item unless they’ve been added individually. So please let us know if you have jewelry, cameras, or other valuables worth more than $2,500 each, so we can cover them fully.

**Comment by unitof** [comment]
“Items commonly used or stored as a set will be treated as a single item, worth the total value of all parts (e.g. a pair earrings, a set of golf clubs, etc.)

Still though, especially with the golf clubs, this makes me worried I could miss out on coverage just by not considering some of my items a "set."

Example: I collect rare books. Nothing I have is near $25,000, but if someone were to steal my library it might be close. Was my library an "item" I should have added individually?

**Comment by ckvo** [comment]
Generally the approach would be if things are normally purchased as a set, they should be considered as a single item. An example that we have used as a test is a camera and lenses. So while a camera with a standard lens would be one item, an additional lens would be a different item. Similarly, in your example of a golf club set, if you had a purchased an additional special driver that would be a separate item to your club set. 

While there will always be edge cases, as we better learn about the points of ambiguity we can refine the language or clarify through the product. Thanks again for the feedback - this is definitely one that we will continue to give consideration to.
