### ISSUE TITLE
Clarification around adding coverage to others living at the same address

### ISSUE THREAD

**Issue by yerich** [lemonade-hq/policy-2.0#4]
Hello,

In the "Who's covered" section, you state the following:

> This policy covers Jane Doe. You can add more people, as long as they permanently live at 5 Crosby St.

After reading the entirety of the rest of the policy, the following questions come to mind:

1) How do I add more people to the policy?
2) How much does it cost, if anything, to add more people to the policy?
3) Are the deductibles separate? That is, say the policy has a deductible of $500, and both I and my parent (who lives in the property full time and is on the policy) both suffer individual losses of $1000. Does the policy pay out $1000, or $1500? What about the annual maximums -- are they joint or separate?

Furthermore, in the "For how much?" section, the coverage limits are described as:

> Damage or theft of your stuff, up to $10,000 in total, and $2,500 per item.

Does "your" in this case refer to only me and thus only my property, or does it also include any others who may be added onto the property?

Thank you.

**Comment by ckvo** [comment]
Hello @yerich! Thanks for the thoughtful comments. Let me answer your questions one at a time:

1. There should be a link on the words "add more people" which will direct you to the right place - most probably our Live Policy. We'll get onto maxing this fix.
2. There will be a cost to add people to the policy but this is something we've yet to finalize. We're focusing on the policy language at the moment.
3. The deductibles apply per event and not per person - so if something happens which affects multiple people on your policy, it's only one deductible. There's no annual max when it comes to the deductible.
4. The coverage amounts cover all people on the policy so users should make sure that they select a limit which is sufficient to reflect everyone on the policy.

Hope this clarifies everything.
