### ISSUE TITLE
Dog Breeds

### ISSUE THREAD

**Issue by 8gloria** [lemonade-hq/policy-2.0#7]
A lot of “vicious” dog breeds are not predisposed biologically or statistically for violence! For instance, chihuahuas are more statistically common to bite, but that’s not there!! I think that if we get our dog certified with full training and socialization, it shouldn’t matter the breed! That’s how State Farm plays it..

**Comment by ckvo** [comment]
Hey @8gloria ! While it's common for the dog breed to determine whether or not there is coverage if it, for example, bites someone, you'll be glad to know that we've actually removed any reference to the dog breed being a determining factor in this version of the policy. We only exclude cases where the dog has a prior bite history.

> Damage that’s related, or similar to, something you’ve been accused of in the past ten years (e.g. your dog has bitten before) isn’t covered.

**Comment by ep4919** [comment]
I have a question about "related, or similar to"....

Say, for example, I have a sidewalk that I've failed to maintain, and someone trips and injures themselves, and files a liability claim against my policy. After that claim I have the sidewalk fixed so it's no longer a tripping hazard, but someone trips anyway and files a claim - would that be considered something I've previously "been accused of" and is no longer covered? So anything I've previously been liable for isn't covered at all regardless of any attempt I've made to mitigate the risk? 

It's not really clear if I'm more-or-less permanently barred from coverage for a prior issue even if I've mitigated the risk.

**Comment by JohnSPeters** [comment]
Hey @ep4919 - This is an issue we've struggled with, in full transparency.  We are trying to avoid someone claims for 'an event' that has started before the policy did - that should be covered by a prior policy.  The 'industry standard' policy says:
> All "bodily injury" and "property damage" resulting from any one accident or from continuous or repeated exposure to substantially the same general harmful conditions shall be considered to be the result of one "occurrence".

We are trying to get to the same concept in simpler words.  So your sidewalk question is a good one.

If you own the sidewalk, and you knew of a hazardous condition and did not fix it, you could be liable.  So if someone hurt themselves a year ago, then you bought the policy, and then someone else hurt themselves, we'd argue the hazardous condition existed before the policy started, you knew about it, and failed to fix it - so not covered.

If you fixed it, and the condition was no longer hazardous, and then it became hazardous again, you could argue that it was a different condition than before and it would be covered. 

The dog parallel might also be a good one.  If your dog bites people regularly - starting before the policy - and you've done nothing to prevent future bites, no coverage.  If you get a different dog, you'd be covered.

Make sense?  Ideas on improving the wording?

**Comment by ep4919** [comment]
Maybe something like: "Damage that's related to, or similar to, something you have been accused of in the past 10 years and you have failed to take steps to remedy the issue. If the hazardous condition existed before the policy started, then we won't cover it after the policy starts." (Then you can put in your "dog has previously bitten someone", "you never fixed that busted sidewalk" examples.)

**Comment by georgieflood** [comment]
We don't cover damage resulting from ongoing or previously identified hazards. 

We don't cover damage resulting from any circumstance or event that has been subject to litigation before the start date of the policy.

That might be a heavier exclusion than you're looking for though, but I think "similar to" is too vague. How similar is similar?

What's interesting is the definition you've quoted from the industry standard language could also be interpreted to mean not that multiple trips on the sidewalk would be excluded within a policy period but that they would be considered to be a single claim event and therefore subject to a single limit (ie $10k for all trips divided amongst trippers, not $10k per trip) 

(full disclosure: I work for an insurance company)

**Comment by georgieflood** [comment]
We do not cover damage caused by previously identified or ongoing hazards.

We do not cover damage caused by circumstances or events that have been the subject of legal action prior to the start date of this policy. 

I think the 10-year limit is oddly arbitrary, and the use of the word 'similar' is too vague. How similar is similar? 

Interestingly, the industry standard definition you cite above could also be interpreted to mean not that multiple instances of tripping on the sidewalk would be excluded within a single policy period but that they would be considered as part of the same claim event and therefore subject to a single limit, (ie, $10k for all tripping divided amongst tripping incidents, not $10k per trip)

(Full disclosure: I work for an insurance company)
